### ISSUE TITLE
[suggestion] oredic recipes and oredic names about sodium

### ISSUE THREAD

**Issue by alxcool** [bence98/SodiumCraft#3]
Hi! While learning more about minecraft mods, I've encountered at least one additional mod than mekanism who inlude sodium as element into their recipes fo forge 1.12.2; gregtech community edition. If I understand it well, acording to gamepedia their might be some more now and there... So I was wondering if someone could rework sodiumcraft to me more inclusive by replacing their current recipe withone who use oredict commutable items and by giving some oredict names fo sodium, sodium hydroxyde, sodium carbonate and nitrite...

My computer hard drive is dying lately, so unless I find a replacement one, I can't do much by myself lately.But if its a matter,let me know if I could replace this issue by a pull request instead  then do it by myself, next time I actually have time for such a thing!

**Comment by bence98** [comment]
Thanks for the suggestion! I actually didn't know about GTCE, but it looks cool! :D
Anyways, OreDict entries have been added, GTCE's and SodiumCraft's sodium dust, sodium hydroxide and sulfide is now mostly compatible.
(However, you cannot use GTCE's items in the Mekanism Chemical Infuser, because Mekanism machines do not yet support OreDictionaried inputs. ThermalExp machines should work just fine.)
